// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVwRhm3PKJCj2YRTB8YwXj1z1WrSNx2mI',
    appId: '1:723455981601:web:4b168eb688f101a134cb60',
    messagingSenderId: '723455981601',
    projectId: 'tracker-b1bd0',
    authDomain: 'tracker-b1bd0.firebaseapp.com',
    storageBucket: 'tracker-b1bd0.firebasestorage.app',
    measurementId: 'G-PVDSTEPYPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsxTraKMvuYV8PkC152GxciM6tqqqYKFY',
    appId: '1:723455981601:android:e77eeadd0562b7fe34cb60',
    messagingSenderId: '723455981601',
    projectId: 'tracker-b1bd0',
    storageBucket: 'tracker-b1bd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQN9A71yt4QT1C7Mk731fZ3iCOjCmsn8o',
    appId: '1:723455981601:ios:967ad963701ca04034cb60',
    messagingSenderId: '723455981601',
    projectId: 'tracker-b1bd0',
    storageBucket: 'tracker-b1bd0.firebasestorage.app',
    iosBundleId: 'com.example.users',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQN9A71yt4QT1C7Mk731fZ3iCOjCmsn8o',
    appId: '1:723455981601:ios:967ad963701ca04034cb60',
    messagingSenderId: '723455981601',
    projectId: 'tracker-b1bd0',
    storageBucket: 'tracker-b1bd0.firebasestorage.app',
    iosBundleId: 'com.example.users',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVwRhm3PKJCj2YRTB8YwXj1z1WrSNx2mI',
    appId: '1:723455981601:web:6b21aa736032dfaa34cb60',
    messagingSenderId: '723455981601',
    projectId: 'tracker-b1bd0',
    authDomain: 'tracker-b1bd0.firebaseapp.com',
    storageBucket: 'tracker-b1bd0.firebasestorage.app',
    measurementId: 'G-4EJ2LLSG9V',
  );
}
